version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_CONNECTION: mysql
          - DB_DATABASE: test_sample01
          - DB_USERNAME: root
      - image: circleci/mysql:5.7-ram

    steps:
      # - run: echo "Hello World"
      - checkout
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run: cp .env.example .env.testing
      - run: echo "APP_KEY=" > .env.testing
      - run: php artisan key:generate
      - run: php artisan migrate
      - run:
          name: php test
          command: vendor/bin/phpunit
