version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_HOST: localhost
          - DB_CONNECTION: mysql_testing
          - DB_DATABASE: test_shortcutrecipe
          - DB_USERNAME: root
          - DB_PASSWORD: root22
      - image: circleci/mysql:8.0-ram
        MYSQL_DATABASE: test_shortcutrecipe
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root22
        TZ: "Asia/Tokyo"

    steps:
      # - run: echo "Hello World"
      - checkout
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm install
      - run: npm run production
      - run: cp .env.example .env.testing
      - run: echo "APP_KEY=" > .env.testing
      - run: php artisan key:generate
      - run: php artisan migrate
      - run:
          name: php test
          command: vendor/bin/phpunit
