version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/mysql:8.0-ram
    environment:
      - DB_CONNECTION: circle_testing

    steps:
      - checkout
      - run: sudo docker-php-ext-install pdo_mysql
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm install
      - run: npm run production
      - run: cp .env.example .env.testing
      # - run: echo "APP_KEY=" > .env.testing
      - run: php artisan key:generate
      - run: php artisan migrate
      - run:
          name: php test
          command: vendor/bin/phpunit
